name: Node.js + Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  nodejs:
    name: Node.js Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Linter
        run: npm run lint --if-present
        working-directory: ./backend

      - name: Run Tests
        run: npm test --if-present
        working-directory: ./backend

      - name: Build Project
        run: npm run build --if-present
        working-directory: ./backend

  flutter:
    name: Flutter Build & Test
    runs-on: ubuntu-latest
    needs: nodejs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0" # adjust to your installed Flutter version

      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./mobile

      - name: Analyze Code
        run: flutter analyze
        working-directory: ./mobile

      - name: Run Tests
        run: flutter test
        working-directory: ./mobile

      - name: Build APK (Release)
        run: flutter build apk --release
        working-directory: ./mobile

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
